registers:
  - name: L1_Voltage
    address: 0
    span: 2
    data_type: FLOAT32
  - name: L1_Current
    address: 0
    span: 2
    data_type: FLOAT32
  - name: TotalPower
    address: 0
    span: 2
    data_type: FLOAT32
writer: json